🚩 add self-updating functionality

diff --git a/ugit b/ugit
--- a/ugit
+++ b/ugit
@@ -1,11 +1,14 @@
 #!/usr/bin/env bash
 
 # ugit: Undo your last oopsie in Git
-# Read the guide: https://bhupesh.gitbook.io/notes/git/how-to-undo-anything-in-git
-
-# TODO: Add self-updating --update #
+# 
 
 set -uo pipefail;
+
+SCRIPT_NAME="$0"
+SCRIPT_URL="https://github.com/Bhupesh-V/ugit/releases/latest/download/ugit"
+TMP_FILE="/tmp/ugit.sh"
+VERSION="1.0"
 
 installed() {
     cmd=$(command -v "${1}")
@@ -26,7 +29,7 @@ for dep in "${deps[@]}"; do
     installed "${dep}" || die "Missing dependency: '${dep}'"
 done
 
-printf "%s\n%s" "$(tput bold)Undo your last oopsie in Git 🙈️$(tput sgr0)" "Contact 📬️: varshneybhupesh@gmail.com for assistance"
+printf "%s\n" "$(tput bold)Undo your last oopsie in Git 🙈️$(tput sgr0)"
 
 display_menu() {
     printf "%s\n" "Undo [git commit]"
@@ -48,7 +51,6 @@ display_menu() {
     printf "%s\n" "Undo/Restore file to a previous commit/version"
 }
 
-option=$(display_menu | nl -n ln | fzf --header="Don't worry we all mess up sometimes" --height 30% --reverse --pointer='ᐅ' --cycle | awk '{print $1}')
 
 undo_git_commit() {
     # TODO: ask which commit to undo?
@@ -202,23 +204,78 @@ restore_file() {
     fi
 }
 
-case $option in
-    1) undo_git_commit;;
-    2) undo_git_push;;
-    3) undo_git_add;;
-    4) undo_git_merge "unpushed";;
-    5) change_commit_message;;
-    6) undo_branch_delete;;
-    7) undo_git_reset;;
-    8) undo_git_merge "conflicts";;
-    9) do_git_reset;;
-    10) undo_git_merge "pushed";;
-    11) recover_lost_stash;;
-    12) undo_git_stash_apply;;
-    13) recover_deleted_tag;;
-    14) do_git_reset "Choose commit just before rebase started";;
-    15) undo_file_delete;;
-    16) undo_file_delete "uncommited";;
-    17) restore_file;;
-esac
+ugit_menu() {
+    case $option in
+        1) undo_git_commit;;
+        2) undo_git_push;;
+        3) undo_git_add;;
+        4) undo_git_merge "unpushed";;
+        5) change_commit_message;;
+        6) undo_branch_delete;;
+        7) undo_git_reset;;
+        8) undo_git_merge "conflicts";;
+        9) do_git_reset;;
+        10) undo_git_merge "pushed";;
+        11) recover_lost_stash;;
+        12) undo_git_stash_apply;;
+        13) recover_deleted_tag;;
+        14) do_git_reset "Choose commit just before rebase started";;
+        15) undo_file_delete;;
+        16) undo_file_delete "uncommited";;
+        17) restore_file;;
+    esac
+}
 
+show_version() {
+    printf "ugit version %s\n" "$VERSION"
+}
+
+print_help() {
+    printf "\n%s\n" "Contact 📬️: varshneybhupesh@gmail.com for assistance"
+    printf "%s\n" "Read the guide: https://bhupesh.gitbook.io/notes/git/how-to-undo-anything-in-git"
+}
+
+ugit_update() {
+    printf "%s\n" "Checking for updates ..."
+    curl -s -L "$SCRIPT_URL" > "$TMP_FILE"
+    NEW_VER=$(grep "^VERSION" "$TMP_FILE" | awk -F'[="]' '{print $3}')
+
+    if [[ "$VERSION" < "$NEW_VER" ]]; then
+        printf "Updating ugit \e[31;1m%s\e[0m -> \e[32;1m%s\e[0m\n" "$VERSION" "$NEW_VER"
+        chmod +x "$TMP_FILE"
+        # WIP
+        if cp "$TMP_FILE" "$SCRIPT_NAME"; then printf "%s\n" "Done"; fi
+        rm -f "$TMP_FILE"
+    else
+        printf "%s\n" "ugit is already at the latest version ($VERSION)"
+        rm -f "$TMP_FILE"
+    fi
+    exit 0
+}
+
+main() {
+    if [[ $# -gt 0 ]]; then
+        local key="$1"
+        case "$key" in
+            --version)
+                show_version
+                ;;
+            --update)
+                ugit_update
+                ;;
+            --help)
+                print_help
+                exit
+                ;;
+            *)
+                printf "%s\n" "ERROR: Unrecognized argument $key"
+                exit 1
+                ;;
+        esac
+    else
+        option=$(display_menu | nl -n ln | fzf --header="Don't worry we all mess up sometimes" --height 30% --reverse --pointer='ᐅ' --cycle | awk '{print $1}')
+        ugit_menu
+    fi
+}
+
+main "$@"
