💥 getting ready for 5.0 release

diff --git a/ugit b/ugit
--- a/ugit
+++ b/ugit
@@ -7,55 +7,50 @@ set -uo pipefail;
 SCRIPT_NAME="$0"
 SCRIPT_URL="https://github.com/Bhupesh-V/ugit/releases/latest/download/ugit"
 TMP_FILE="/tmp/ugit.sh"
-VERSION="4.1"
+VERSION="5.0"
 
-installed() {
-    cmd=$(command -v "${1}")
-
-    [[ -n "${cmd}" ]] && [[ -f "${cmd}" ]]
-    return ${?}
-}
-
-die() {
-    >&2 echo "Fatal: $*"
-    exit 1
-}
-
-[[ "${BASH_VERSINFO[0]}" -lt 4 ]] && die "Bash >=4 required"
-
-deps=(fzf git awk xargs cut nl tput)
-for dep in "${deps[@]}"; do
-    installed "${dep}" || die "Missing dependency: '${dep}'"
-done
-
+BOLD_ORG_FG=$(tput bold)$(tput setaf 208)
+BOLD=$(tput bold)
+RESET=$(tput sgr0)
 
 display_menu() {
-    printf "%s\n" "Undo [git commit]"
-    printf "%s\n" "Undo [git push]"
-    printf "%s\n" "Undo [git add]"
-    printf "%s\n" "Undo [git pull]"
-    printf "%s\n" "Undo/Change [git commit message]"
-    printf "%s\n" "Undo local branch delete [git branch -d]"
-    printf "%s\n" "Undo [git reset]"
+    printf "%s\n" "Undo ${BOLD_ORG_FG}git commit${RESET}"
+    printf "%s\n" "Undo ${BOLD_ORG_FG}git push${RESET}"
+    printf "%s\n" "Undo ${BOLD_ORG_FG}git add${RESET}"
+    printf "%s\n" "Undo ${BOLD_ORG_FG}git pull${RESET}"
+    printf "%s\n" "Undo/Change git commit message"
+    printf "%s\n" "Undo local branch delete ${BOLD_ORG_FG}git branch -d${RESET}"
+    printf "%s\n" "Undo ${BOLD_ORG_FG}git reset${RESET}"
     printf "%s\n" "Undo a Merge with Conflicts"
     printf "%s\n" "Undo an Unpushed Merge Commit"
     printf "%s\n" "Undo a Pushed Merge Commit"
-    printf "%s\n" "Undo [git stash pop/drop/clear]"
-    printf "%s\n" "Undo [git stash apply]"
-    printf "%s\n" "Undo tag delete [git tag -d]"
-    printf "%s\n" "Undo [git rebase]"
+    printf "%s\n" "Undo ${BOLD_ORG_FG}git stash pop/drop/clear${RESET}"
+    printf "%s\n" "Undo ${BOLD_ORG_FG}git stash apply${RESET}"
+    printf "%s\n" "Undo tag delete ${BOLD_ORG_FG}git tag -d${RESET}"
+    printf "%s\n" "Undo ${BOLD_ORG_FG}git rebase${RESET}"
     printf "%s\n" "Undo/Recover commited file delete"
     printf "%s\n" "Undo/Recover uncommited file delete"
-    printf "%s\n" "Undo/Restore file to a previous commit/version"
-    printf "%s\n" "Undo [git cherry-pick]"
+    printf "%s\n" "Undo/Restore file to a previous commit"
+    printf "%s\n" "Undo ${BOLD_ORG_FG}git cherry-pick${RESET}"
     printf "%s\n" "Undo all current uncommited changes"
 }
 
+perror() {
+    printf "%s\n" "$(tput bold)$(tput setaf 196)ugit error${RESET}: $1"
+}
 
 undo_git_commit() {
     # undo last commit (don't unstage everything)
     # git reset --soft HEAD^
-    commit=$(git log --oneline | fzf --ansi --height 10% --reverse --multi --header="Choose commit to undo" | awk '{print $1}')
+    commit=$(git log --color --oneline | fzf --ansi --height 80% \
+        --reverse --multi --header="Choose commit to undo" \
+        --preview "echo {} | cut -d' ' -f1 | xargs -I{} git show --color --pretty=format:%b {}" \
+        --bind 'j:down,k:up,ctrl-j:preview-down,ctrl-k:preview-up,ctrl-space:toggle-preview' --preview-window right:60% \
+        | awk '{print $1}')
+
+    # exit if no commit selected
+    [ -z "$commit" ] && exit
+
     last_commit=$(git log --format="%h" -n 1)
 
     if [[ "$last_commit" == "$commit" ]]; then
@@ -63,7 +58,7 @@ undo_git_commit() {
             printf "%s\n" "Commit: $last_commit successfully undone"
         fi
     elif git revert "$commit"; then
-        printf "%s\n" "Commit: $commit successfully reverted. Check 'git status'"
+        printf "%s\n" "Commit: $commit successfully reverted. Check ${BOLD_ORG_FG}git status${RESET}"
     fi
 }
 
@@ -72,61 +67,70 @@ do_git_reset() {
     FZF_HEADER=${1:-"Choose last good branch commit"}
     last_good_state=$(git reflog | fzf --ansi --height 20% --reverse --header="$FZF_HEADER" | awk '{print $1}')
     # check if working tree is clean or not
-    [[ $(git status --porcelain 2>/dev/null) ]] && read -p "You have uncommited changes, still proceed? [Y/n]: " -n 1 -r USER_INPUT
+    [[ $(git status --porcelain 2>/dev/null) != "" ]] && read -p "You have uncommited changes, still proceed? [Y/n]: " -n 1 -r USER_INPUT
     USER_INPUT=${USER_INPUT:-Y}
     [[ "$USER_INPUT" == Y ]] && git reset --hard "$last_good_state"
 }
 
 undo_git_add() {
     # show prompt to unstage files interactively
-    # choices=$(git ls-files | fzf --height 10% --reverse --multi --marker='🢂' --color 'marker:#B8CC52' --header="Choose files to unstage (TAB to select multiple files)")
-    readarray -t choices < <(git ls-files | fzf --height 10% --reverse --multi --marker='🢂' --color 'marker:#B8CC52' --header="Choose files to unstage (TAB to select multiple files)")
-    # declare -p choices
-    git restore --staged "${choices[@]}"
+    readarray -t choices < <(git ls-files 2> /dev/null | fzf --height 10% --reverse --multi \
+        --marker='🢂 ' --color 'marker:#B8CC52' \
+        --prompt="Choose files to unstage: " \
+        --header="Use TAB to select multiple files")
+
+    if [[ ${#choices[@]} -gt 0 ]] && git restore --staged "${choices[@]}"; then
+        printf "%s\n" "Done 👍️"
+    fi
 }
 
 change_commit_message() {
     printf "%s" "Enter New Commit Message (Ctrl+d to save):"
     msg=$(</dev/stdin)
     echo
-    [[ "$msg" ]] && git commit --amend -m "$msg" || printf "%s" "Empty Commit string!"
+    [[ "$msg" ]] && git commit --amend -m "$msg" || perror "Empty Commit string!"
 }
 
 undo_git_push() {
-    commit=$(git log --oneline | fzf --ansi --height 10% --reverse --multi --header="Choose Commit hash to revert/undo" | awk '{print $1}')
+    commit=$(git log --oneline | fzf --ansi --height 10% --reverse --multi --header="Choose Commit to revert/undo" | awk '{print $1}')
     if git revert "$commit"; then
         printf "%s\n" "Commit: $commit successfully reverted."
-        printf "%s\n" "Make sure to run 'git push' now"
+        printf "%s\n" "Make sure to run ${BOLD_ORG_FG}git push${RESET} now!"
     fi
 }
 
 undo_branch_delete() {
     # undo local branch delete
-    last_branch_commit=$(git reflog | fzf --ansi --height 20% --reverse --multi --header="Choose last good branch commit" | awk '{print $1}')
-    # echo "$last_branch_commit"
+    last_branch_commit=$(git reflog | fzf --ansi --height 20% --reverse --multi \
+        --header="Choose last good branch commit" --prompt="ugit can only branches deleted locally" | awk '{print $1}')
+
     read -p "Enter Branch Name: " -r BRANCH_NAME
-    if git checkout -b "$BRANCH_NAME" "$last_branch_commit"; then
-        printf "%s\n" "Branch $BRANCH_NAME successfully recovered"
+    if [ ! -z "$BRANCH_NAME" ] && git checkout -b "$BRANCH_NAME" "$last_branch_commit"; then
+        printf "%s\n" "Branch $BRANCH_NAME successfully recovered 👍️"
+    else
+        perror "Error: unable to perform operation"
     fi
 }
 
 undo_git_reset() {
     LAST_GOOD_STATE=$(git reflog | fzf --ansi --height 20% --reverse --multi --header="Choose last known good commit" | awk '{print $1}')
-    git reset "$LAST_GOOD_STATE"
+    if [[ ! -z "$LAST_GOOD_STATE" ]] && git reset "$LAST_GOOD_STATE"; then
+        printf "%s\n" "Reset to $LAST_GOOD_STATE 👍️"
+    fi
 }
 
 undo_git_merge() {
     # Undoing a git merge is a messy business
     printf "%s\n" "Tips: "
-    printf "%s\n" "Do a revert of the previous revert if the faulty side branch was fixed by adding corrections on top."
-    printf "%s\n" "Re-merge the result branch if the faulty side branch (discarded by an earlier revert of a merge) was rebuilt from scratch (i.e. rebasing and fixing)."
+    printf "%s\n" "Do a revert of the previous revert if the faulty side branch was fixed by adding corrections on top"
+    printf "%s\n" "Re-merge the result branch if the faulty side branch (discarded by an earlier revert of a merge) was rebuilt from scratch (i.e. rebasing and fixing)"
     if [[ "$1" == "conflicts" ]]; then
         git merge --abort
     elif [[ "$1" == "unpushed" ]]; then
         # FROM: https://stackoverflow.com/questions/1223354/undo-git-pull-how-to-bring-repos-to-old-state
         # last_good_state=$(git reflog | fzf --ansi --height 20% --reverse --header="Choose the merge commit" | awk '{print $1}')
         # check if working tree is clean or not
-        [[ $(git status --porcelain 2>/dev/null) ]] && read -p "You have uncommited changes, still proceed? [Y/n]: " -n 1 -r USER_INPUT
+        [[ $(git status --porcelain 2>/dev/null) != "" ]] && read -p "You have uncommited changes, still proceed? [Y/n]: " -n 1 -r USER_INPUT
         USER_INPUT=${USER_INPUT:-Y}
         # ref: ORIG_HEAD points to the original commit from before the merge
         [[ "$USER_INPUT" == Y ]] && git reset --merge ORIG_HEAD || exit 0
@@ -137,30 +141,39 @@ undo_git_merge() {
         git checkout "$default_branch"
         commit=$(git log --oneline | fzf --ansi --height 10% --reverse --header="Choose the merge commit" | awk '{print $1}')
         if git revert -m 1 "$commit"; then
-            printf "%s\n" "Merge ($commit) successfully reverted"
+            printf "%s\n" "Merge ($commit) successfully reverted 👍️"
         fi
     fi
 }
 
 recover_lost_stash() {
-    LOST_STASH=$(git fsck --no-progress --unreachable | grep commit | cut -d ' ' -f3 | xargs git log --oneline --merges --no-walk | fzf --ansi --height 20% --reverse --header="Choose commit associated with stash" | awk '{print $1}')
-    read -p "Enter Stash Message/Comment: " -r STASH_MSG
+    LOST_STASH=$(git fsck --no-progress --unreachable | \
+        awk '/commit/ {print $3}' | \
+        xargs git log --color --oneline --merges --no-walk | \
+        fzf --ansi --height 20% --reverse --header="Choose commit associated with stash" | awk '{print $1}'
+    )
+
+    [[ "$LOST_STASH" ]] && read -p "Enter Stash Description: " -r STASH_MSG || exit
+
     if git update-ref refs/stash "$LOST_STASH" --create-reflog -m "$STASH_MSG"; then
-        printf "%s\n" "Stash Successfully Recovered"
-        git stash list | grep "$STASH_MSG"
+        printf "%s\n" "Stash Successfully Recovered 👍️"
+    else
+        perror "Unable to recover stash"
     fi
 }
 
 undo_git_stash_apply() {
-    # check if diff coloring is set to auto in git config if not the reverse apply command will fail
+    # check if diff coloring is set to auto in git config, 
+    # if not the reverse apply command will fail
     is_diff_color=$(git config --get color.diff | tr -d '\n')
     if [[ "$is_diff_color" == "auto" ]]; then
         if git stash show -p | git apply --reverse; then
             printf "%s\n" "Done 👍️"
         fi
     else
+        perror "Undoing git stash apply failed"
         printf "%s\n" "Please change diff color to auto in .gitconfig & run ugit again"
-        printf "%s\n" "Or use the following command [git config --global color.diff \"auto\"]"
+        printf "%s\n" "Or use the following command ${BOLD}git config --global color.diff \"auto\"${RESET}"
     fi
 }
 
@@ -181,50 +194,73 @@ recover_deleted_tag() {
     elif git update-ref refs/tags/"$TAG_NAME" --create-reflog "$COMMIT"; then
         printf "%s\n" "Tag $TAG_NAME Successfully Recovered 👍️"
     else
-        printf "%s\n" "Unable to recover deleted tag $TAG_NAME"
+        perror "Unable to recover deleted tag $TAG_NAME"
     fi
 }
 
 undo_file_delete() {
-    if [[ "$1" == "uncommited" ]]; then
+    if [[ "$1" = "uncommited" ]]; then
         # user didn't commit the file deletion
         DELETED_FILE=$(git ls-files -d | fzf --ansi --height 20% --reverse --header="Choose deleted file to recover" | awk '{print $1}')
         if git checkout HEAD "$DELETED_FILE"; then
-            printf "%s\n" "$DELETED_FILE Successfully Recovered 👍️"
+            printf "%s\n" "${BOLD}$DELETED_FILE${RESET} Successfully Recovered 👍️"
             exit 0
         fi
-    else
+    elif [[ "$1" = "commited" ]]; then
         read -p "Enter complete filename: " -r FILENAME
-        COMMIT=$(git log --diff-filter=D --oneline | fzf --ansi --height 20% --reverse --header="Choose commit that deleted $FILENAME" | awk '{print $1}')
+        COMMIT=$(git log --color --diff-filter=D --oneline | fzf --ansi --height 50% \
+            --reverse --prompt="Choose commit that deleted ${BOLD_ORG_FG}$FILENAME${RESET}: " \
+            --header="Use ctrl-j/ctrl-k to navigate file preview. ctrl+space to toggle preview" \
+            --preview "echo {} | cut -d' ' -f1 | xargs -I{} git show --color --pretty=format:%b {}" \
+            --bind 'j:down,k:up,ctrl-j:preview-down,ctrl-k:preview-up,ctrl-space:toggle-preview' --preview-window right:50% \
+            | awk '{print $1}')
+
+        [[ -z "$COMMIT" ]] && exit
+
         if git checkout "$COMMIT"~1 -- "$FILENAME"; then
-            printf "%s\n" "$FILENAME Successfully Recovered 👍️"
+            printf "%s\n" "${BOLD}$FILENAME${RESET} Successfully Recovered 👍️"
         fi
     fi
 }
 
 restore_file() {
-    FILE=$(git ls-files | fzf --ansi --height 20% --reverse --header="Choose file to restore" | awk '{print $1}')
-    COMMIT=$(git log --oneline "$FILE" | fzf --ansi --height 80% --reverse --prompt="Choose commit to restore file to" --header="Use ctrl-j/ctrl-k to navigate file preview. ctrl+space to toggle preview" --preview "echo {} | cut -d' ' -f1 | xargs -I{} git show {}:$FILE" --bind 'j:down,k:up,ctrl-j:preview-down,ctrl-k:preview-up,ctrl-space:toggle-preview' --preview-window down:60%)
-    COMMIT=$(printf "%s" "$COMMIT" | awk '{print $1}')
+    FILE=$(git ls-files | fzf --ansi --height 20% --reverse --header="Choose a file to restore" | awk '{print $1}')
+
+    if [[ ! -z "$FILE" ]]; then
+        COMMIT=$(git log --color --oneline "$FILE" | fzf --ansi --height 80% --reverse \
+            --prompt="Choose a previous commit for ${BOLD_ORG_FG}$FILE${RESET}: " \
+            --header="Use ctrl-j/ctrl-k to navigate file preview. ctrl+space to toggle preview" \
+            --preview "echo {} | cut -d' ' -f1 | xargs -I{} git show --color {}:$FILE" \
+            --bind 'j:down,k:up,ctrl-j:preview-down,ctrl-k:preview-up,ctrl-space:toggle-preview' --preview-window right:50%)
+
+        COMMIT=$(printf "%s" "$COMMIT" | awk '{print $1}')
+    else
+        exit
+    fi
 
     if ! git diff -s --quiet "$FILE"; then
-        # check if any local changes
+        # check for any local changes
         printf "%s\n" "$FILE seems to be modified. Please either commit or discard those changes."
         exit 0
-    elif git restore --source="$COMMIT" "$FILE"; then
-        printf "%s\n" "$FILE restored to version at $COMMIT"
+    elif [[ "$COMMIT" != "" && "$FILE" != "" ]] && git restore --source="$COMMIT" "$FILE"; then
+        printf "%s\n" "$FILE restored to version at ${BOLD}$COMMIT${RESET}"
     fi
 }
 
 undo_all() {
     # TODO: Ask user for permanent deletion (use git clean for this)
+    if [[ $(git status --porcelain 2>/dev/null) == "" ]]; then
+        printf "%s\n" "Working history already clean 👌"
+        exit
+    fi
+
     printf "%s\n" "Stashing current changes ..."
     read -p "Enter Stash Description (optional): " -r STASH_MSG
     if git stash save -au "${STASH_MSG}"; then
         # TODO: only display this if there are untracked changes (new files)
         # printf "%s\n" "Note: Stashing untracked files might take some time, hold on"
         printf "%s\n" "Cleared all changes 👍️"
-        printf "%s\n" "Run 'git stash apply' to redo changes or 'git stash drop' to remove them"
+        printf "%s\n" "Run ${BOLD_ORG_FG}git stash apply${RESET} to redo changes or ${BOLD_ORG_FG}git stash drop${RESET} to remove them"
     fi
 }
 
@@ -244,12 +280,35 @@ ugit_menu() {
         12) undo_git_stash_apply;;
         13) recover_deleted_tag;;
         14) do_git_reset "Choose commit just before rebase started";;
-        15) undo_file_delete;;
+        15) undo_file_delete "commited";;
         16) undo_file_delete "uncommited";;
         17) restore_file;;
         18) undo_git_commit;;
         19) undo_all;;
     esac
+}
+
+installed() {
+    cmd=$(command -v "${1}")
+
+    [[ -n "${cmd}" ]] && [[ -f "${cmd}" ]]
+    return ${?}
+}
+
+die() {
+    >&2 echo "Fatal: $*"
+    exit 1
+}
+
+check_deps() {
+    # check dependencies to run ugit
+
+    [[ "${BASH_VERSINFO[0]}" -lt 4 ]] && die "Bash >=4 required"
+
+    deps=(fzf git awk xargs cut nl tput)
+    for dep in "${deps[@]}"; do
+        installed "${dep}" || die "Missing dependency: '${dep}'"
+    done
 }
 
 show_version() {
@@ -270,9 +329,9 @@ Available options:
 -u, --update    Update ugit
 -g, --guide     Open ugit undo text guide
 EOF
-printf "\n%s\n" "Contact 📬️: $(tput bold)varshneybhupesh@gmail.com$(tput sgr0) for assistance"
+printf "\n%s\n" "Contact 📬️: $(tput bold)varshneybhupesh@gmail.com${RESET} for assistance"
 printf "%s\n" "Read the guide: https://bhupesh.gitbook.io/notes/git/how-to-undo-anything-in-git"
-printf "\n%s\n" "Please give us ⭐ a if you liked ugit $(tput bold)$(tput setaf 208)https://github.com/Bhupesh-V/ugit$(tput sgr0)"
+printf "\n%s\n" "Please give us ⭐ a if you liked ugit ${BOLD_ORG_FG}https://github.com/Bhupesh-V/ugit${RESET}"
 }
 
 ugit_update() {
@@ -296,16 +355,28 @@ ugit_update() {
 open_guide() {
     GUIDE="https://bhupesh.gitbook.io/notes/git/how-to-undo-anything-in-git"
 
-    case "$(uname)" in
-        Linux ) xdg-open > /dev/null 2>&1 "$GUIDE";;
-        Darwin ) open "$GUIDE" ;;
-        *) printf "%s\n" "Guide: $GUIDE"
+    case "$OSTYPE" in
+        darwin*)
+            # MacOS
+            open $GUIDE;;
+        msys)
+            # Git Bash on Windows
+            start $GUIDE;;
+        linux*)
+            # Handle WSL on Windows
+            if uname -a | grep -i -q Microsoft; then
+                powershell.exe -NoProfile start $GUIDE
+            else
+                xdg-open > /dev/null 2>&1 $GUIDE
+            fi;;
+        *)
+            xdg-open > /dev/null 2>&1 $GUIDE;;
     esac
 }
 
 header() {
-    printf "%s\n" "$(tput bold)Undo your last oopsie in Git 🙈️$(tput sgr0)"
-    printf "%s\n" "$(tput setaf 248)Press ctrl+c to exit anytime $(tput sgr0)"
+    printf "%s\n" "$(tput bold)Undo your last oopsie in Git 🙈️${RESET}"
+    printf "%s\n" "$(tput setaf 248)Press ctrl+c to exit anytime ${RESET}"
 }
 
 init_test() {
@@ -337,9 +408,10 @@ main() {
                 exit 1;;
         esac
     else
+        check_deps
         init_test
         header
-        option=$(display_menu | nl -n ln | fzf --header="Don't worry we all mess up sometimes" --height 30% --reverse --pointer='👉' --cycle | awk '{print $1}')
+        option=$(display_menu | nl -n ln | fzf --header="Don't worry we all mess up sometimes" --height 50% --ansi --reverse --pointer='👉' --cycle | awk '{print $1}')
         ugit_menu
     fi
 }
